/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by tools/gen-reasons. DO NOT EDIT.

package events

// AllReasons returns every declared Reason in declaration order. It is
// the catalog-membership list cross-checked by the orchestration suite
// and the events-catalog-membership linter. Generated from package
// events' exported Reason consts by tools/gen-reasons; run `make generate`
// to refresh after adding or removing a Reason.
func AllReasons() []Reason {
	return []Reason{
		SecretRotated,
		SecretRotationFailed,
		SecretRotationPartial,
		AuthSecretShortPassword,
		PodsCoLocated,
		PDBTooPermissive,
		MaxUnavailableInsteadOfMin,
		AntiAffinityTooPermissive,
		RolloutFragileQuorum,
		RolloutGraceTooTight,
		WarnAggressiveTimeouts,
		FailoverSuppressed,
		FailoverInitiated,
		FailoverSucceeded,
		FailoverSucceededWithTimeout,
		FailoverAborted,
		FailoverStalled,
		UnexpectedFailover,
		SplitBrainDetected,
		OperatorStarted,
		WebhookCertRotated,
		WebhookCertRotationFailed,
		BootstrapCompleted,
		BootstrapConfigMapUpdated,
		ReplicaAnnounceIPUpdated,
		ConfigDrift,
		ConfigMapRecreated,
		DegradedResolved,
		FieldDeprecated,
		PVCResizeInitiated,
		PVCResizeComplete,
		PVCExpansionShrinkRejected,
		PVCExpansionNotSupported,
		PVCExpansionFailed,
		PVCExpansionStuck,
		PVCResizeAborted,
		PVCMissing,
		PodLabelReconciled,
		ReplicationGatePatched,
		ReplicationGateCheckFailed,
		ReplicationPrimaryLost,
		NoMasterAgreement,
		OrphanMasterDemoted,
		OrphanMasterDemotionFailed,
		PrimaryClientsDropped,
		PrimaryClientsDropFailed,
		OrphanMasterDataDivergence,
		AllValkeyPodsDown,
		StaleReplicaEscapeDeleted,
		ScaleRefused,
		ScalePrecheckFailed,
		ScaleDeferred,
		PodRolledForConfig,
		RolloutDeferred,
		RolloutStarted,
		RolloutCompleted,
		QuorumLost,
		QuorumReached,
		RolloutAbortedQuorumLost,
		RolloutResumed,
		RolloutStalled,
		ReplicasRolled,
		PrimaryRolloutBlocked,
		SpecChangeDeferred,
		NoSuitableReplica,
		DualMasterSelfHealInitiated,
		DualMasterSelfHealDemoted,
		DualMasterSelfHealDeferred,
		DualMasterObserved,
		SentinelSTSRestartNeeded,
		SentinelResetIssued,
		SentinelResetFailed,
		SentinelResetAllFailed,
		SentinelAuthApplied,
		SentinelAuthNotApplied,
		InitialSentinelReset,
		SentinelMonitorIssued,
		SentinelMonitorFailed,
		SentinelTuningFailed,
		SentinelStrandedRecovery,
		SentinelDeadMasterRepoint,
		SentinelStaleEpochRepoint,
		RecoveryPromotionInitiated,
		RecoveryPromotionFailed,
		SentinelPeerLinkupStuck,
		SentinelTopologyMismatch,
		SentinelObserverReconnect,
		SentinelPubsubMessageLost,
		SentinelRollDeferred,
		ValkeyImageTransitionRejected,
		ValkeyImageTransitionWarning,
		ValkeyImageTransitionOverridden,
	}
}
