/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Command gen-reasons regenerates the events-catalog membership list
// (internal/events/zz_generated.reasons.go) from the package's exported
// Reason-typed consts, in declaration order. It is the single source of
// truth for AllReasons(): the list can no longer drift from the consts.
//
// It mirrors the events-catalog-membership linter's accept set — every
// exported const whose declared type is `Reason` — but emits the slice in
// source-declaration order (files sorted by name, declarations in source
// order) so the result is deterministic across regenerations and any future
// file split of the catalog. Wired into `make generate`; CI's generate-diff
// gate fails if a new Reason const lands without a regenerate.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// reasonTypeName is the named type that marks a const as a catalog reason.
const reasonTypeName = "Reason"

func main() {
	src := flag.String("src", "internal/events", "package directory to scan for Reason consts")
	out := flag.String("out", "internal/events/zz_generated.reasons.go", "output file to write")
	header := flag.String("header", "tools/boilerplate.go.txt", "license header file to prepend")
	flag.Parse()

	if err := run(*src, *out, *header); err != nil {
		fmt.Fprintln(os.Stderr, "gen-reasons:", err)
		os.Exit(1)
	}
}

func run(srcDir, out, header string) error {
	names, err := collectReasons(srcDir, filepath.Base(out))
	if err != nil {
		return err
	}
	if len(names) == 0 {
		return fmt.Errorf("no exported %s consts found in %s", reasonTypeName, srcDir)
	}
	src, err := render(header, names)
	if err != nil {
		return err
	}
	return os.WriteFile(out, src, 0o644)
}

// collectReasons parses every non-test .go file in srcDir (excluding the
// generated output) and returns the names of all exported consts whose
// declared type is Reason, in declaration order. Files are visited in sorted
// name order; within a file, declarations keep their source order.
func collectReasons(srcDir, outBase string) ([]string, error) {
	entries, err := os.ReadDir(srcDir)
	if err != nil {
		return nil, err
	}
	var files []string
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") ||
			strings.HasSuffix(name, "_test.go") || name == outBase {
			continue
		}
		files = append(files, name)
	}
	sort.Strings(files)

	fset := token.NewFileSet()
	var names []string
	for _, f := range files {
		path := filepath.Join(srcDir, f)
		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.CONST {
				continue
			}
			for _, spec := range gd.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				// Only consts with an explicit `Reason` type join the
				// catalog — exactly what makes the membership linter's
				// picker exact. Untyped string consts are intentionally
				// excluded; iota-inherited types never produce a string.
				id, ok := vs.Type.(*ast.Ident)
				if !ok || id.Name != reasonTypeName {
					continue
				}
				for _, n := range vs.Names {
					if n.IsExported() {
						names = append(names, n.Name)
					}
				}
			}
		}
	}
	return names, nil
}

func render(header string, names []string) ([]byte, error) {
	hdr, err := os.ReadFile(header)
	if err != nil {
		return nil, err
	}

	var b bytes.Buffer
	b.Write(hdr)
	b.WriteString("\n// Code generated by tools/gen-reasons. DO NOT EDIT.\n\n")
	b.WriteString("package events\n\n")
	b.WriteString("// AllReasons returns every declared Reason in declaration order. It is\n")
	b.WriteString("// the catalog-membership list cross-checked by the orchestration suite\n")
	b.WriteString("// and the events-catalog-membership linter. Generated from package\n")
	b.WriteString("// events' exported Reason consts by tools/gen-reasons; run `make generate`\n")
	b.WriteString("// to refresh after adding or removing a Reason.\n")
	b.WriteString("func AllReasons() []Reason {\n\treturn []Reason{\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\t\t%s,\n", n)
	}
	b.WriteString("\t}\n}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}
