/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AuthRotationStatusApplyConfiguration represents a declarative configuration of the AuthRotationStatus type for use
// with apply.
//
// AuthRotationStatus is the persisted substate for the auth-Secret
// hot-rotation flow. The reconciler edge-detects a Secret content
// change by comparing the current Secret's password-bytes hash against
// the most recently observed hash stored here; on first observation
// it stamps the hash and stays Idle. On a real change it walks the
// data plane (replicas first, master last) via internal/valkey.RotateAuth
// and transitions through InProgress → Succeeded; on partial failure
// it reverts the successfully-updated pods and transitions to Failed
// (revert succeeded, cluster back on the prior credential) or Partial
// (revert also failed; cluster in mixed-credential state, requires
// human intervention). The hash compare is over the Secret content
// (the `password` data key) — resourceVersion alone false-triggers
// on metadata-only edits.
type AuthRotationStatusApplyConfiguration struct {
	// Phase is the current substate.
	Phase *string `json:"phase,omitempty"`
	// ObservedSecretHash is the hex-encoded SHA-256 of the auth Secret
	// password content the operator most recently observed (and, in
	// the Succeeded case, fully applied across the data plane). The
	// next reconcile compares the current Secret's hash against this
	// to edge-detect a content change. Empty until the first
	// observation. Hashing the password content (not the Secret bytes
	// or resourceVersion) avoids false triggers on metadata-only edits
	// and lets the field persist across operator restarts without
	// storing the password itself.
	//
	// Privacy caveat: SHA-256 is not a password hash (no salt, no
	// KDF). For strong, high-entropy passwords this hash is brute-
	// force resistant — it serves only as a content-change marker.
	// For weak passwords (low entropy, dictionary-derived) the hash
	// is reversible via offline brute-force or rainbow tables.
	// Status is world-readable to anyone with `get/list valkeys` on
	// the namespace, so weak passwords leak through this field.
	// Operators are expected to use auth Secrets meeting the
	// project's MinTokenLen entropy gate; the redaction registry
	// emits a warning event on shorter passwords.
	ObservedSecretHash *string `json:"observedSecretHash,omitempty"`
	// StartedAt timestamps the most recent transition into InProgress.
	StartedAt *v1.Time `json:"startedAt,omitempty"`
	// LastTransitionAt timestamps the most recent phase change.
	LastTransitionAt *v1.Time `json:"lastTransitionAt,omitempty"`
	// Message is a short human-readable description of the current
	// phase, including (for Failed/Partial) a summary of the affected
	// endpoints so an operator can map the substate back to specific
	// pods without consulting events.
	Message *string `json:"message,omitempty"`
}

// AuthRotationStatusApplyConfiguration constructs a declarative configuration of the AuthRotationStatus type for use with
// apply.
func AuthRotationStatus() *AuthRotationStatusApplyConfiguration {
	return &AuthRotationStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *AuthRotationStatusApplyConfiguration) WithPhase(value string) *AuthRotationStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithObservedSecretHash sets the ObservedSecretHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedSecretHash field is set to the value of the last call.
func (b *AuthRotationStatusApplyConfiguration) WithObservedSecretHash(value string) *AuthRotationStatusApplyConfiguration {
	b.ObservedSecretHash = &value
	return b
}

// WithStartedAt sets the StartedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartedAt field is set to the value of the last call.
func (b *AuthRotationStatusApplyConfiguration) WithStartedAt(value v1.Time) *AuthRotationStatusApplyConfiguration {
	b.StartedAt = &value
	return b
}

// WithLastTransitionAt sets the LastTransitionAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTransitionAt field is set to the value of the last call.
func (b *AuthRotationStatusApplyConfiguration) WithLastTransitionAt(value v1.Time) *AuthRotationStatusApplyConfiguration {
	b.LastTransitionAt = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *AuthRotationStatusApplyConfiguration) WithMessage(value string) *AuthRotationStatusApplyConfiguration {
	b.Message = &value
	return b
}
