/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// AuthSpecApplyConfiguration represents a declarative configuration of the AuthSpec type for use
// with apply.
//
// AuthSpec references Secrets carrying valkey and (optional) sentinel auth.
type AuthSpecApplyConfiguration struct {
	// SecretName is the Secret containing the Valkey default-user password.
	SecretName *string `json:"secretName,omitempty"`
	SecretKey  *string `json:"secretKey,omitempty"`
	// SentinelAuthSecretName is a separate Secret holding the sentinel
	// auth-user / auth-pass pair. Permitted only when mode=sentinel.
	SentinelAuthSecretName *string `json:"sentinelAuthSecretName,omitempty"`
	SentinelAuthSecretKey  *string `json:"sentinelAuthSecretKey,omitempty"`
}

// AuthSpecApplyConfiguration constructs a declarative configuration of the AuthSpec type for use with
// apply.
func AuthSpec() *AuthSpecApplyConfiguration {
	return &AuthSpecApplyConfiguration{}
}

// WithSecretName sets the SecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretName field is set to the value of the last call.
func (b *AuthSpecApplyConfiguration) WithSecretName(value string) *AuthSpecApplyConfiguration {
	b.SecretName = &value
	return b
}

// WithSecretKey sets the SecretKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretKey field is set to the value of the last call.
func (b *AuthSpecApplyConfiguration) WithSecretKey(value string) *AuthSpecApplyConfiguration {
	b.SecretKey = &value
	return b
}

// WithSentinelAuthSecretName sets the SentinelAuthSecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SentinelAuthSecretName field is set to the value of the last call.
func (b *AuthSpecApplyConfiguration) WithSentinelAuthSecretName(value string) *AuthSpecApplyConfiguration {
	b.SentinelAuthSecretName = &value
	return b
}

// WithSentinelAuthSecretKey sets the SentinelAuthSecretKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SentinelAuthSecretKey field is set to the value of the last call.
func (b *AuthSpecApplyConfiguration) WithSentinelAuthSecretKey(value string) *AuthSpecApplyConfiguration {
	b.SentinelAuthSecretKey = &value
	return b
}
