/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// FailoverDispatchStatusApplyConfiguration represents a declarative configuration of the FailoverDispatchStatus type for use
// with apply.
//
// FailoverDispatchStatus is the durable mirror of the operator's
// in-memory failover-in-flight latch. It records that
// runPrimaryRolloutDispatch stripped `role=primary` off the outgoing
// primary and dispatched `SENTINEL FAILOVER`, written to status BEFORE
// the strip so an operator crash between the strip and the observer's
// `+switch-master` does not lose the in-flight record. On the next
// reconcile the suppression latch is rehydrated from this marker, so
// `role=primary` is not re-stamped on the pre-strip primary mid-election
// — which would reopen the write-to-old-primary window the strip-first
// ordering exists to close.
type FailoverDispatchStatusApplyConfiguration struct {
	// PreStripAddr is the observer-reported primary `ip:port` captured
	// the instant before the `role=primary` strip. While the live
	// observer snapshot still reports this address the election has not
	// completed and role re-stamping stays suppressed; the marker clears
	// when the snapshot moves off it.
	//
	// The pattern accepts an IPv4 or bracketed-IPv6 host with a numeric
	// port — the operator writes `net.JoinHostPort` form (`10.0.0.1:6379`
	// or `[fe80::1]:6379`) — so it rejects an obviously-malformed
	// hand-edited value at admission rather than silently no-op'ing on
	// the deadline backstop, without rejecting a valid IPv6 address.
	PreStripAddr *string `json:"preStripAddr,omitempty"`
	// Deadline bounds how long the durable suppression holds. Sized at
	// the in-memory latch TTL (the sentinel failover-timeout default plus
	// an observer-tick allowance). Past it a wedged failover no longer
	// suppresses re-derivation — the next reconcile clears the marker and
	// re-derives the primary from observation.
	Deadline *v1.Time `json:"deadline,omitempty"`
	// PreStripEpoch is the monotonic fencing token: the Sentinel
	// config-epoch the operator observed the instant before stripping
	// role=primary, recorded here at strip time. An observation or action
	// carrying a LOWER epoch is a stale view of an election this dispatch
	// already superseded and is refused — it must not exit the critical
	// section or seed a primary from a pre-failover snapshot. Best-effort:
	// zero when the config-epoch could not be parsed at strip time, in
	// which case the fence is inert (no observation is refused).
	PreStripEpoch *int64 `json:"preStripEpoch,omitempty"`
}

// FailoverDispatchStatusApplyConfiguration constructs a declarative configuration of the FailoverDispatchStatus type for use with
// apply.
func FailoverDispatchStatus() *FailoverDispatchStatusApplyConfiguration {
	return &FailoverDispatchStatusApplyConfiguration{}
}

// WithPreStripAddr sets the PreStripAddr field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PreStripAddr field is set to the value of the last call.
func (b *FailoverDispatchStatusApplyConfiguration) WithPreStripAddr(value string) *FailoverDispatchStatusApplyConfiguration {
	b.PreStripAddr = &value
	return b
}

// WithDeadline sets the Deadline field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deadline field is set to the value of the last call.
func (b *FailoverDispatchStatusApplyConfiguration) WithDeadline(value v1.Time) *FailoverDispatchStatusApplyConfiguration {
	b.Deadline = &value
	return b
}

// WithPreStripEpoch sets the PreStripEpoch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PreStripEpoch field is set to the value of the last call.
func (b *FailoverDispatchStatusApplyConfiguration) WithPreStripEpoch(value int64) *FailoverDispatchStatusApplyConfiguration {
	b.PreStripEpoch = &value
	return b
}
