/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ImageSpecApplyConfiguration represents a declarative configuration of the ImageSpec type for use
// with apply.
//
// ImageSpec pins the container image for each component.
//
// Per-component repository/tag defaults are applied by the defaulting
// webhook (stampImageDefaults), not by schema `+kubebuilder:default`
// markers — keeping the authoritative default in operator code so bumping a
// default tag in a new release does not bake into the published CRD OpenAPI
// or re-apply to existing CRs through the apiserver's schema defaulting. The
// `omitzero` tag option (Go 1.24+) plus `omitempty` keep a zero-valued
// component out of the wire form (the webhook stamps it server-side from the
// deserialized object regardless), so a Go client marshalling
// `Spec{Mode: standalone}` does not emit noisy `image:{valkey:{},…}`.
type ImageSpecApplyConfiguration struct {
	// Valkey server image. Repository/tag default via the webhook when unset.
	Valkey *ContainerImageApplyConfiguration `json:"valkey,omitempty"`
	// Sentinel image — a single Valkey binary; defaults to the Valkey image.
	Sentinel *ContainerImageApplyConfiguration `json:"sentinel,omitempty"`
	// Exporter image. Only pulled when spec.metrics.enabled=true.
	Exporter *ContainerImageApplyConfiguration `json:"exporter,omitempty"`
}

// ImageSpecApplyConfiguration constructs a declarative configuration of the ImageSpec type for use with
// apply.
func ImageSpec() *ImageSpecApplyConfiguration {
	return &ImageSpecApplyConfiguration{}
}

// WithValkey sets the Valkey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Valkey field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithValkey(value *ContainerImageApplyConfiguration) *ImageSpecApplyConfiguration {
	b.Valkey = value
	return b
}

// WithSentinel sets the Sentinel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sentinel field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithSentinel(value *ContainerImageApplyConfiguration) *ImageSpecApplyConfiguration {
	b.Sentinel = value
	return b
}

// WithExporter sets the Exporter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exporter field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithExporter(value *ContainerImageApplyConfiguration) *ImageSpecApplyConfiguration {
	b.Exporter = value
	return b
}
