/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MasterAwareRolloutStatusApplyConfiguration represents a declarative configuration of the MasterAwareRolloutStatus type for use
// with apply.
//
// MasterAwareRolloutStatus is the persisted watchdog substate for the
// master-aware rolling-update flow. The operator stamps WaitingForPod
// subsequent reconcile checks the deadline against now() and emits
// RolloutStalled + sets Degraded=True reason=RolloutStalled if the pod
// hasn't become Ready by then. The per-pod replicaReadyTimeoutSeconds
// floor is enforced in the validating webhook (60s) and ceiling
// (3600s); the operator clamps to those bounds defensively.
type MasterAwareRolloutStatusApplyConfiguration struct {
	// WaitingForPod is the name of the pod the operator is currently
	// waiting on. Empty means no pod-deletion is in flight (so the
	// watchdog is inactive even if Deadline is set, which is a transient
	// post-clear state). The pod name is sufficient for the watchdog
	// because the StatefulSet recreates pods at the same name.
	WaitingForPod *string `json:"waitingForPod,omitempty"`
	// Deadline is the wall-clock cutoff for the replacement pod to
	// reach Ready. Set to (DeletedAt + spec.rollout.replicaReadyTimeoutSeconds)
	// at deletion time. A nil Deadline means the watchdog is inactive
	// (paired with WaitingForPod == "").
	Deadline *v1.Time `json:"deadline,omitempty"`
	// DeletedAt timestamps the pod-deletion that armed this watchdog.
	// Surfaced for kubectl get observability and for log-line context;
	// the deadline computation reads only Deadline.
	DeletedAt *v1.Time `json:"deletedAt,omitempty"`
}

// MasterAwareRolloutStatusApplyConfiguration constructs a declarative configuration of the MasterAwareRolloutStatus type for use with
// apply.
func MasterAwareRolloutStatus() *MasterAwareRolloutStatusApplyConfiguration {
	return &MasterAwareRolloutStatusApplyConfiguration{}
}

// WithWaitingForPod sets the WaitingForPod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WaitingForPod field is set to the value of the last call.
func (b *MasterAwareRolloutStatusApplyConfiguration) WithWaitingForPod(value string) *MasterAwareRolloutStatusApplyConfiguration {
	b.WaitingForPod = &value
	return b
}

// WithDeadline sets the Deadline field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deadline field is set to the value of the last call.
func (b *MasterAwareRolloutStatusApplyConfiguration) WithDeadline(value v1.Time) *MasterAwareRolloutStatusApplyConfiguration {
	b.Deadline = &value
	return b
}

// WithDeletedAt sets the DeletedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletedAt field is set to the value of the last call.
func (b *MasterAwareRolloutStatusApplyConfiguration) WithDeletedAt(value v1.Time) *MasterAwareRolloutStatusApplyConfiguration {
	b.DeletedAt = &value
	return b
}
