/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// PDBSpecApplyConfiguration represents a declarative configuration of the PDBSpec type for use
// with apply.
//
// PDBSpec overrides the derived PodDisruptionBudget. Defaults to
// `minAvailable = replicas - 1` when unset. Setting both MinAvailable
// and MaxUnavailable on a single PDB is rejected by the Kubernetes
// PodDisruptionBudget API itself; mirroring that rejection at admission
// time gives a clearer error than waiting for the downstream PDB create
// to fail.
type PDBSpecApplyConfiguration struct {
	MinAvailable *intstr.IntOrString `json:"minAvailable,omitempty"`
	// MaxUnavailable is mutually exclusive with MinAvailable.
	MaxUnavailable *intstr.IntOrString `json:"maxUnavailable,omitempty"`
}

// PDBSpecApplyConfiguration constructs a declarative configuration of the PDBSpec type for use with
// apply.
func PDBSpec() *PDBSpecApplyConfiguration {
	return &PDBSpecApplyConfiguration{}
}

// WithMinAvailable sets the MinAvailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinAvailable field is set to the value of the last call.
func (b *PDBSpecApplyConfiguration) WithMinAvailable(value intstr.IntOrString) *PDBSpecApplyConfiguration {
	b.MinAvailable = &value
	return b
}

// WithMaxUnavailable sets the MaxUnavailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxUnavailable field is set to the value of the last call.
func (b *PDBSpecApplyConfiguration) WithMaxUnavailable(value intstr.IntOrString) *PDBSpecApplyConfiguration {
	b.MaxUnavailable = &value
	return b
}
