/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// PersistenceSpecApplyConfiguration represents a declarative configuration of the PersistenceSpec type for use
// with apply.
//
// PersistenceSpec describes the PVC backing a valkey pod.
//
// Toggling persistence on or off after a CR has bootstrapped is not
// supported at v1beta1: K8s makes StatefulSet.spec.volumeClaimTemplates
// immutable on Update, so flipping the field on an existing CR will
// be rejected by the apiserver during the operator's next SSA apply.
// Either set Persistence at create time, or delete and recreate the
// CR (with pvcRetentionPolicy=Retain on the original if data preservation
// matters across the gap). Resize of an already-persistent CR via
// `size` is the supported in-place mutation, driven by the
// operator's PVC resize sub-state-machine (internal/pvcresize).
type PersistenceSpecApplyConfiguration struct {
	StorageClass *string                         `json:"storageClass,omitempty"`
	Size         *resource.Quantity              `json:"size,omitempty"`
	AccessModes  []v1.PersistentVolumeAccessMode `json:"accessModes,omitempty"`
}

// PersistenceSpecApplyConfiguration constructs a declarative configuration of the PersistenceSpec type for use with
// apply.
func PersistenceSpec() *PersistenceSpecApplyConfiguration {
	return &PersistenceSpecApplyConfiguration{}
}

// WithStorageClass sets the StorageClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageClass field is set to the value of the last call.
func (b *PersistenceSpecApplyConfiguration) WithStorageClass(value string) *PersistenceSpecApplyConfiguration {
	b.StorageClass = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *PersistenceSpecApplyConfiguration) WithSize(value resource.Quantity) *PersistenceSpecApplyConfiguration {
	b.Size = &value
	return b
}

// WithAccessModes adds the given value to the AccessModes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AccessModes field.
func (b *PersistenceSpecApplyConfiguration) WithAccessModes(values ...v1.PersistentVolumeAccessMode) *PersistenceSpecApplyConfiguration {
	for i := range values {
		b.AccessModes = append(b.AccessModes, values[i])
	}
	return b
}
