/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// PodMonitorSpecApplyConfiguration represents a declarative configuration of the PodMonitorSpec type for use
// with apply.
//
// PodMonitorSpec is opt-in PodMonitor scraping.
type PodMonitorSpecApplyConfiguration struct {
	// Enabled toggles PodMonitor emission. `*bool` for the same
	// explicit-vs-unset reason as ReadinessGateSpec.Enabled.
	Enabled        *bool   `json:"enabled,omitempty"`
	ScrapeInterval *string `json:"scrapeInterval,omitempty"`
}

// PodMonitorSpecApplyConfiguration constructs a declarative configuration of the PodMonitorSpec type for use with
// apply.
func PodMonitorSpec() *PodMonitorSpecApplyConfiguration {
	return &PodMonitorSpecApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *PodMonitorSpecApplyConfiguration) WithEnabled(value bool) *PodMonitorSpecApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithScrapeInterval sets the ScrapeInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScrapeInterval field is set to the value of the last call.
func (b *PodMonitorSpecApplyConfiguration) WithScrapeInterval(value string) *PodMonitorSpecApplyConfiguration {
	b.ScrapeInterval = &value
	return b
}
