/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PVCResizeStatusApplyConfiguration represents a declarative configuration of the PVCResizeStatus type for use
// with apply.
//
// PVCResizeStatus is the persisted substate for the PVC resize flow.
//
// Phases progress linearly:
//
// # Detected → Validated → StsOrphaned → PVCsPatched → StsRecreated → Verified
//
// Any substate may transition to Aborted on a terminal failure (shrink reject,
// missing allowVolumeExpansion, CSI 422, 10-minute substate stall). On Aborted
// the next reconcile retries from Detected after a backoff that scales with
// Attempt and is capped at one hour.
type PVCResizeStatusApplyConfiguration struct {
	// Phase is the current substate.
	Phase *string `json:"phase,omitempty"`
	// Attempt counts how many times the resize flow has restarted from
	// Detected after an Aborted state. Drives the inter-attempt backoff
	// (exponential, capped at 1h).
	Attempt *int32 `json:"attempt,omitempty"`
	// StartedAt timestamps the first transition into Detected for the
	// current attempt.
	StartedAt *v1.Time `json:"startedAt,omitempty"`
	// LastTransitionAt timestamps the most recent phase change. Used by
	// the per-substate 10-minute stall guard.
	LastTransitionAt *v1.Time `json:"lastTransitionAt,omitempty"`
	// LastStuckEventAt timestamps the most recent PVCExpansionStuck
	// event emission for the current stall window. Used to dedup the
	// stuck-event emission across reconciles: once the per-substate
	// stall threshold (10 minutes since LastTransitionAt) is crossed,
	// the dispatcher emits one event and stamps this field, then
	// suppresses further emissions until the substate moves (which
	// refreshes LastTransitionAt and so resets the dedup window).
	// Without this dedup the event would re-fire every requeue (~5s)
	// once stalled, drowning the events stream.
	LastStuckEventAt *v1.Time `json:"lastStuckEventAt,omitempty"`
	// Message is a short human-readable description of the current phase,
	// including the reason for the most recent Aborted transition.
	Message *string `json:"message,omitempty"`
}

// PVCResizeStatusApplyConfiguration constructs a declarative configuration of the PVCResizeStatus type for use with
// apply.
func PVCResizeStatus() *PVCResizeStatusApplyConfiguration {
	return &PVCResizeStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *PVCResizeStatusApplyConfiguration) WithPhase(value string) *PVCResizeStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithAttempt sets the Attempt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Attempt field is set to the value of the last call.
func (b *PVCResizeStatusApplyConfiguration) WithAttempt(value int32) *PVCResizeStatusApplyConfiguration {
	b.Attempt = &value
	return b
}

// WithStartedAt sets the StartedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartedAt field is set to the value of the last call.
func (b *PVCResizeStatusApplyConfiguration) WithStartedAt(value v1.Time) *PVCResizeStatusApplyConfiguration {
	b.StartedAt = &value
	return b
}

// WithLastTransitionAt sets the LastTransitionAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTransitionAt field is set to the value of the last call.
func (b *PVCResizeStatusApplyConfiguration) WithLastTransitionAt(value v1.Time) *PVCResizeStatusApplyConfiguration {
	b.LastTransitionAt = &value
	return b
}

// WithLastStuckEventAt sets the LastStuckEventAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastStuckEventAt field is set to the value of the last call.
func (b *PVCResizeStatusApplyConfiguration) WithLastStuckEventAt(value v1.Time) *PVCResizeStatusApplyConfiguration {
	b.LastStuckEventAt = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *PVCResizeStatusApplyConfiguration) WithMessage(value string) *PVCResizeStatusApplyConfiguration {
	b.Message = &value
	return b
}
