/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ReadinessGateSpecApplyConfiguration represents a declarative configuration of the ReadinessGateSpec type for use
// with apply.
//
// ReadinessGateSpec gates pod readiness on replication health.
type ReadinessGateSpecApplyConfiguration struct {
	// Enabled toggles the gate. The defaulting webhook stamps `false` for
	// standalone and `true` for replication/sentinel; `*bool` lets the
	// webhook distinguish "user opted out (`enabled: false`)" from
	// "user left the field unset" (round-trip stable through
	// `kubectl apply`).
	Enabled *bool `json:"enabled,omitempty"`
	// MaxLagBytes is the maximum permitted `master_repl_offset -
	// slave_repl_offset` before the replica pod is considered Ready.
	// `*int64` lets the defaulter distinguish "user left the field
	// unset" (stamped to 1 MiB) from "user wants a tighter or looser
	// bound" (preserved verbatim, including `maxLagBytes: 0` — which
	// the validator warns about because zero lag tolerance means a
	// replica would never go Ready).
	MaxLagBytes *int64 `json:"maxLagBytes,omitempty"`
}

// ReadinessGateSpecApplyConfiguration constructs a declarative configuration of the ReadinessGateSpec type for use with
// apply.
func ReadinessGateSpec() *ReadinessGateSpecApplyConfiguration {
	return &ReadinessGateSpecApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ReadinessGateSpecApplyConfiguration) WithEnabled(value bool) *ReadinessGateSpecApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithMaxLagBytes sets the MaxLagBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxLagBytes field is set to the value of the last call.
func (b *ReadinessGateSpecApplyConfiguration) WithMaxLagBytes(value int64) *ReadinessGateSpecApplyConfiguration {
	b.MaxLagBytes = &value
	return b
}
