/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// RolloutSpecApplyConfiguration represents a declarative configuration of the RolloutSpec type for use
// with apply.
//
// RolloutSpec governs rolling-update behaviour.
type RolloutSpecApplyConfiguration struct {
	// MaxUnavailable pods during rolling update. The validating webhook
	// emits a Warning when set above 1 (quorum-fragility risk).
	MaxUnavailable *int32 `json:"maxUnavailable,omitempty"`
	// FailoverGracePeriodSeconds caps the wait for `+failover-end` during
	// master-aware rolling. Zero means "use default at reconcile time"
	// (sentinel.failoverTimeout + 30s).
	FailoverGracePeriodSeconds *int32 `json:"failoverGracePeriodSeconds,omitempty"`
	// ReplicaReadyTimeoutSeconds caps how long the rollout waits for a
	// replacement replica pod to become Ready after its old incarnation is
	// deleted. Timeout transitions the state machine to Degraded.
	ReplicaReadyTimeoutSeconds *int32 `json:"replicaReadyTimeoutSeconds,omitempty"`
	// MaxLagBytes is the per-replica `master_repl_offset -
	// slave_repl_offset` ceiling tolerated before the rolling-update
	// advances to the next pod. Distinct from
	// ReadinessGateSpec.MaxLagBytes (steady-state ceiling, 1 MiB
	// default); this knob applies during the rolling-update window only,
	// where slightly larger lag is acceptable in exchange for keeping
	// the rollout moving.
	MaxLagBytes *int64 `json:"maxLagBytes,omitempty"`
}

// RolloutSpecApplyConfiguration constructs a declarative configuration of the RolloutSpec type for use with
// apply.
func RolloutSpec() *RolloutSpecApplyConfiguration {
	return &RolloutSpecApplyConfiguration{}
}

// WithMaxUnavailable sets the MaxUnavailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxUnavailable field is set to the value of the last call.
func (b *RolloutSpecApplyConfiguration) WithMaxUnavailable(value int32) *RolloutSpecApplyConfiguration {
	b.MaxUnavailable = &value
	return b
}

// WithFailoverGracePeriodSeconds sets the FailoverGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailoverGracePeriodSeconds field is set to the value of the last call.
func (b *RolloutSpecApplyConfiguration) WithFailoverGracePeriodSeconds(value int32) *RolloutSpecApplyConfiguration {
	b.FailoverGracePeriodSeconds = &value
	return b
}

// WithReplicaReadyTimeoutSeconds sets the ReplicaReadyTimeoutSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplicaReadyTimeoutSeconds field is set to the value of the last call.
func (b *RolloutSpecApplyConfiguration) WithReplicaReadyTimeoutSeconds(value int32) *RolloutSpecApplyConfiguration {
	b.ReplicaReadyTimeoutSeconds = &value
	return b
}

// WithMaxLagBytes sets the MaxLagBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxLagBytes field is set to the value of the last call.
func (b *RolloutSpecApplyConfiguration) WithMaxLagBytes(value int64) *RolloutSpecApplyConfiguration {
	b.MaxLagBytes = &value
	return b
}
