/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// RolloutStatusApplyConfiguration represents a declarative configuration of the RolloutStatus type for use
// with apply.
//
// RolloutStatus carries the substate of any operator-driven rollout in flight.
// Currently only the PVC-resize substate is wired; future rollout flavors
// (config-change, image bump, primary failover) attach their own fields here.
type RolloutStatusApplyConfiguration struct {
	// PVCResize tracks the orphan-delete-recreate substate for the PVC
	// resize flow. Set on resize intent detection; cleared once the flow
	// reaches Verified.
	PVCResize *PVCResizeStatusApplyConfiguration `json:"pvcResize,omitempty"`
	// MasterAware tracks the per-pod readiness watchdog for the
	// master-aware rolling-update flow. Set when the operator deletes a
	// data-plane pod during a rollout step (replica or primary); cleared
	// when the replacement pod becomes Ready or the watchdog declares
	// the rollout stalled. Drives the RolloutStalled event + transition
	// to Degraded when the deadline passes without the replacement
	// reaching Ready.
	MasterAware *MasterAwareRolloutStatusApplyConfiguration `json:"masterAware,omitempty"`
	// AuthRotation tracks the auth-Secret hot-rotation substate. Set
	// when an auth-Secret content change is detected; transitions
	// through InProgress → Succeeded (then settles to Idle) or, on
	// partial-success, into Failed (rotation reverted) or Partial
	// (revert also failed; cluster in mixed-credential state and
	// requires operator intervention). Empty / Idle when no rotation
	// is in flight.
	AuthRotation *AuthRotationStatusApplyConfiguration `json:"authRotation,omitempty"`
	// SuspendedFrom records the rollout state in flight at the moment
	// the CR transitioned into Degraded on quorum loss. Stamped on the
	// abort edge (RolloutPending → Degraded stamps "RolloutPending";
	// RolloutReplicas → Degraded stamps "RolloutReplicas") and cleared
	// on the recovery edges out of Degraded (Degraded → Steady or
	// Degraded → RolloutPending). Drives the rollout-state-machine
	// dispatch between the DegradedResolved and RolloutResumed events,
	// so the audit trail can distinguish "abort was from a pending
	// rollout, recovery resumed it cleanly" from "abort was from steady
	// state, recovery returned cleanly". Empty when no rollout was in
	// flight at the abort, or after recovery has cleared it.
	SuspendedFrom *string `json:"suspendedFrom,omitempty"`
	// FailoverDispatch records a strip-then-`SENTINEL FAILOVER` that was
	// in flight on the operator-driven primary-rollout path. The operator
	// strips `role=primary` off the outgoing primary before issuing the
	// failover (so the `<cr>` Service stops routing writes during the
	// election); this marker is written durably right before that strip,
	// so an operator crash mid-election self-heals deterministically
	// instead of relying on observer-snapshot timing. The next operator's
	// reconcile rehydrates its in-memory failover-suppression latch from
	// this marker and does not re-stamp `role=primary` on the pre-strip
	// primary while the election is still in progress. Cleared once the
	// observer confirms the new primary (the snapshot address moves off
	// the pre-strip address) or the marker deadline passes. Empty when no
	// failover is in flight.
	FailoverDispatch *FailoverDispatchStatusApplyConfiguration `json:"failoverDispatch,omitempty"`
}

// RolloutStatusApplyConfiguration constructs a declarative configuration of the RolloutStatus type for use with
// apply.
func RolloutStatus() *RolloutStatusApplyConfiguration {
	return &RolloutStatusApplyConfiguration{}
}

// WithPVCResize sets the PVCResize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PVCResize field is set to the value of the last call.
func (b *RolloutStatusApplyConfiguration) WithPVCResize(value *PVCResizeStatusApplyConfiguration) *RolloutStatusApplyConfiguration {
	b.PVCResize = value
	return b
}

// WithMasterAware sets the MasterAware field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MasterAware field is set to the value of the last call.
func (b *RolloutStatusApplyConfiguration) WithMasterAware(value *MasterAwareRolloutStatusApplyConfiguration) *RolloutStatusApplyConfiguration {
	b.MasterAware = value
	return b
}

// WithAuthRotation sets the AuthRotation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthRotation field is set to the value of the last call.
func (b *RolloutStatusApplyConfiguration) WithAuthRotation(value *AuthRotationStatusApplyConfiguration) *RolloutStatusApplyConfiguration {
	b.AuthRotation = value
	return b
}

// WithSuspendedFrom sets the SuspendedFrom field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuspendedFrom field is set to the value of the last call.
func (b *RolloutStatusApplyConfiguration) WithSuspendedFrom(value string) *RolloutStatusApplyConfiguration {
	b.SuspendedFrom = &value
	return b
}

// WithFailoverDispatch sets the FailoverDispatch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailoverDispatch field is set to the value of the last call.
func (b *RolloutStatusApplyConfiguration) WithFailoverDispatch(value *FailoverDispatchStatusApplyConfiguration) *RolloutStatusApplyConfiguration {
	b.FailoverDispatch = value
	return b
}
