/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// SentinelPodSpecApplyConfiguration represents a declarative configuration of the SentinelPodSpec type for use
// with apply.
//
// SentinelPodSpec is the sentinel pod shape. Reachable only when mode=sentinel
// (gated by enclosing CEL rules); kept in v1beta1 schema so the relaxation
// in the sentinel stage is enum-only, not a schema additive change.
// Timing floors (downAfterMilliseconds >= 1000 and failoverTimeout >= 180000)
// are enforced by the validating webhook (`validateSentinelTimingFloors` in
// internal/webhook/v1beta1/) instead of CEL — the webhook can read
// `metadata.annotations` to honour the `velkir.ioxie.dev/allow-aggressive-timeouts=true`
// override, which CEL bound to `self` (the SentinelPodSpec) cannot. See #102.
// The downAfterMilliseconds floor was lowered from 30000 to 1000 in #461
// after empirical recovery-SLO measurements showed the 30000 default
// (Sentinel's documented "production safe" value) forced a ~36s recovery
// floor unreachable for sub-15s SLOs; 1s is conservative against
// false-positive failovers on stable in-cluster networks while making
// 6-10s recovery achievable. Values <1000 still require the annotation.
// Defense-in-depth: duplicates the `Minimum=1` field-level marker on
// ParallelSyncs so the constraint survives a future field-level
// relaxation.
// The masterName regex follows Sentinel's own naming rules (the value
// passed to `SENTINEL MONITOR <name> ...`), not RFC-1035: a leading digit
// and trailing hyphen are both legal because Sentinel itself accepts
// them. Valkey never derives a Kubernetes resource name from masterName
// (Service names use the CR name), so the looser shape is safe.
type SentinelPodSpecApplyConfiguration struct {
	// MasterName is passed to sentinel as `SENTINEL MONITOR <masterName> ...`.
	// Required, no default, immutable.
	MasterName *string `json:"masterName,omitempty"`
	Replicas   *int32  `json:"replicas,omitempty"`
	// Quorum. The defaulting webhook stamps `ceil((replicas+1)/2)` when zero.
	Quorum *int32 `json:"quorum,omitempty"`
	// DownAfterMilliseconds is forwarded verbatim to sentinel.conf as
	// `sentinel down-after-milliseconds`. Defines the wait before
	// Sentinel marks the monitored master as +sdown. Practical recovery
	// floor is approximately `DownAfterMilliseconds + 6s` (quorum
	// gathering + election + label-flip + EndpointSlice propagation).
	// Default 3000 (3s) supports a sub-10s recovery SLO on stable
	// in-cluster networks; raise to 30000 (30s) for noisier
	// environments where brief blips would otherwise trigger
	// false-positive failovers. Floor is 1000 (1s); the validating
	// webhook rejects lower values unless the
	// `velkir.ioxie.dev/allow-aggressive-timeouts=true` annotation is set
	// (and emits a warning event when it is).
	DownAfterMilliseconds *int32 `json:"downAfterMilliseconds,omitempty"`
	FailoverTimeout       *int32 `json:"failoverTimeout,omitempty"`
	ParallelSyncs         *int32 `json:"parallelSyncs,omitempty"`
	// PDB overrides the derived PodDisruptionBudget. Default
	// `minAvailable = replicas - 1` when unset.
	PDB       *PDBSpecApplyConfiguration `json:"pdb,omitempty"`
	Resources *v1.ResourceRequirements   `json:"resources,omitempty"`
	// CustomLivenessProbe overrides the operator's default TCP liveness
	// probe for the sentinel container. Intended for tuning the timing
	// fields (period / failureThreshold / timeout) of the restart window;
	// the defaulter stamps a tcpSocket probe with a ~60s anti-flap grace
	// when this is unset.
	CustomLivenessProbe *v1.Probe `json:"customLivenessProbe,omitempty"`
	// CustomReadinessProbe overrides the operator's default TCP readiness
	// probe. Readiness is deliberately TCP-only — never coupled to quorum
	// state — so a sentinel with degraded quorum still accepts client
	// discovery; the default drops a wedged sentinel out of discovery in
	// ~15s without restarting it.
	CustomReadinessProbe      *v1.Probe                     `json:"customReadinessProbe,omitempty"`
	Affinity                  *v1.Affinity                  `json:"affinity,omitempty"`
	Tolerations               []v1.Toleration               `json:"tolerations,omitempty"`
	NodeSelector              map[string]string             `json:"nodeSelector,omitempty"`
	TopologySpreadConstraints []v1.TopologySpreadConstraint `json:"topologySpreadConstraints,omitempty"`
	PriorityClassName         *string                       `json:"priorityClassName,omitempty"`
	DNSConfig                 *v1.PodDNSConfig              `json:"dnsConfig,omitempty"`
	PodAnnotations            map[string]string             `json:"podAnnotations,omitempty"`
	PodLabels                 map[string]string             `json:"podLabels,omitempty"`
	SecurityContext           *v1.PodSecurityContext        `json:"securityContext,omitempty"`
}

// SentinelPodSpecApplyConfiguration constructs a declarative configuration of the SentinelPodSpec type for use with
// apply.
func SentinelPodSpec() *SentinelPodSpecApplyConfiguration {
	return &SentinelPodSpecApplyConfiguration{}
}

// WithMasterName sets the MasterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MasterName field is set to the value of the last call.
func (b *SentinelPodSpecApplyConfiguration) WithMasterName(value string) *SentinelPodSpecApplyConfiguration {
	b.MasterName = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *SentinelPodSpecApplyConfiguration) WithReplicas(value int32) *SentinelPodSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithQuorum sets the Quorum field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Quorum field is set to the value of the last call.
func (b *SentinelPodSpecApplyConfiguration) WithQuorum(value int32) *SentinelPodSpecApplyConfiguration {
	b.Quorum = &value
	return b
}

// WithDownAfterMilliseconds sets the DownAfterMilliseconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DownAfterMilliseconds field is set to the value of the last call.
func (b *SentinelPodSpecApplyConfiguration) WithDownAfterMilliseconds(value int32) *SentinelPodSpecApplyConfiguration {
	b.DownAfterMilliseconds = &value
	return b
}

// WithFailoverTimeout sets the FailoverTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailoverTimeout field is set to the value of the last call.
func (b *SentinelPodSpecApplyConfiguration) WithFailoverTimeout(value int32) *SentinelPodSpecApplyConfiguration {
	b.FailoverTimeout = &value
	return b
}

// WithParallelSyncs sets the ParallelSyncs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ParallelSyncs field is set to the value of the last call.
func (b *SentinelPodSpecApplyConfiguration) WithParallelSyncs(value int32) *SentinelPodSpecApplyConfiguration {
	b.ParallelSyncs = &value
	return b
}

// WithPDB sets the PDB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PDB field is set to the value of the last call.
func (b *SentinelPodSpecApplyConfiguration) WithPDB(value *PDBSpecApplyConfiguration) *SentinelPodSpecApplyConfiguration {
	b.PDB = value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *SentinelPodSpecApplyConfiguration) WithResources(value v1.ResourceRequirements) *SentinelPodSpecApplyConfiguration {
	b.Resources = &value
	return b
}

// WithCustomLivenessProbe sets the CustomLivenessProbe field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomLivenessProbe field is set to the value of the last call.
func (b *SentinelPodSpecApplyConfiguration) WithCustomLivenessProbe(value v1.Probe) *SentinelPodSpecApplyConfiguration {
	b.CustomLivenessProbe = &value
	return b
}

// WithCustomReadinessProbe sets the CustomReadinessProbe field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomReadinessProbe field is set to the value of the last call.
func (b *SentinelPodSpecApplyConfiguration) WithCustomReadinessProbe(value v1.Probe) *SentinelPodSpecApplyConfiguration {
	b.CustomReadinessProbe = &value
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *SentinelPodSpecApplyConfiguration) WithAffinity(value v1.Affinity) *SentinelPodSpecApplyConfiguration {
	b.Affinity = &value
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *SentinelPodSpecApplyConfiguration) WithTolerations(values ...v1.Toleration) *SentinelPodSpecApplyConfiguration {
	for i := range values {
		b.Tolerations = append(b.Tolerations, values[i])
	}
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *SentinelPodSpecApplyConfiguration) WithNodeSelector(entries map[string]string) *SentinelPodSpecApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithTopologySpreadConstraints adds the given value to the TopologySpreadConstraints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TopologySpreadConstraints field.
func (b *SentinelPodSpecApplyConfiguration) WithTopologySpreadConstraints(values ...v1.TopologySpreadConstraint) *SentinelPodSpecApplyConfiguration {
	for i := range values {
		b.TopologySpreadConstraints = append(b.TopologySpreadConstraints, values[i])
	}
	return b
}

// WithPriorityClassName sets the PriorityClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PriorityClassName field is set to the value of the last call.
func (b *SentinelPodSpecApplyConfiguration) WithPriorityClassName(value string) *SentinelPodSpecApplyConfiguration {
	b.PriorityClassName = &value
	return b
}

// WithDNSConfig sets the DNSConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DNSConfig field is set to the value of the last call.
func (b *SentinelPodSpecApplyConfiguration) WithDNSConfig(value v1.PodDNSConfig) *SentinelPodSpecApplyConfiguration {
	b.DNSConfig = &value
	return b
}

// WithPodAnnotations puts the entries into the PodAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodAnnotations field,
// overwriting an existing map entries in PodAnnotations field with the same key.
func (b *SentinelPodSpecApplyConfiguration) WithPodAnnotations(entries map[string]string) *SentinelPodSpecApplyConfiguration {
	if b.PodAnnotations == nil && len(entries) > 0 {
		b.PodAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PodAnnotations[k] = v
	}
	return b
}

// WithPodLabels puts the entries into the PodLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodLabels field,
// overwriting an existing map entries in PodLabels field with the same key.
func (b *SentinelPodSpecApplyConfiguration) WithPodLabels(entries map[string]string) *SentinelPodSpecApplyConfiguration {
	if b.PodLabels == nil && len(entries) > 0 {
		b.PodLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PodLabels[k] = v
	}
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *SentinelPodSpecApplyConfiguration) WithSecurityContext(value v1.PodSecurityContext) *SentinelPodSpecApplyConfiguration {
	b.SecurityContext = &value
	return b
}
