/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// SentinelQuorumSpecApplyConfiguration represents a declarative configuration of the SentinelQuorumSpec type for use
// with apply.
//
// SentinelQuorumSpec is operator-set, immutable bookkeeping that binds
// a SentinelQuorum record to the sentinel pod it reports for and its
// parent Valkey CR. The operator creates one SentinelQuorum per
// sentinel pod at bootstrap and never updates the spec afterwards.
//
// Pull-model architecture: sentinel pods are not K8s API clients —
// they speak only the Valkey protocol. The operator observes them
// in-process (internal/sentinel/observer.go) and is the sole intended
// writer of SentinelQuorum status. There is no peer-impersonation
// path because the sentinel pods cannot reach the apiserver at all.
type SentinelQuorumSpecApplyConfiguration struct {
	// Valkey is the name of the parent Valkey CR this record reports for.
	// Set by the operator at create time and immutable afterwards (the
	// CEL rule on the type root enforces). Cross-Valkey reuse of a
	// SentinelQuorum record would break the aggregation invariant
	// (operator aggregates per-Valkey).
	Valkey *string `json:"valkey,omitempty"`
	// PodName is the name of the sentinel pod this record reports
	// for. Set by the operator at create time and immutable
	// afterwards. The 1:1 SQ-name-to-pod-name mapping lets a reader
	// correlate each record with its pod via `kubectl get
	// sentinelquorums` without a separate derivation step.
	PodName *string `json:"podName,omitempty"`
}

// SentinelQuorumSpecApplyConfiguration constructs a declarative configuration of the SentinelQuorumSpec type for use with
// apply.
func SentinelQuorumSpec() *SentinelQuorumSpecApplyConfiguration {
	return &SentinelQuorumSpecApplyConfiguration{}
}

// WithValkey sets the Valkey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Valkey field is set to the value of the last call.
func (b *SentinelQuorumSpecApplyConfiguration) WithValkey(value string) *SentinelQuorumSpecApplyConfiguration {
	b.Valkey = &value
	return b
}

// WithPodName sets the PodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodName field is set to the value of the last call.
func (b *SentinelQuorumSpecApplyConfiguration) WithPodName(value string) *SentinelQuorumSpecApplyConfiguration {
	b.PodName = &value
	return b
}
