/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SentinelQuorumStatusApplyConfiguration represents a declarative configuration of the SentinelQuorumStatus type for use
// with apply.
//
// SentinelQuorumStatus carries one sentinel pod's view of the
// topology — which valkey pod it sees as primary, which replicas it
// can reach, and whether it has enough peer-sentinels online to form
// quorum. The operator reads + aggregates these per-Valkey records to
// drive the failover state machine and `Valkey.Status` updates.
//
// Writer: the operator is the sole intended writer (pull model — see
// the type-level godoc above). Status writer wiring from the operator
// observer is forward-compat; aggregation reads tolerate empty/stale
// status by reporting Unknown, so unwired records do not surface as
// a failure.
type SentinelQuorumStatusApplyConfiguration struct {
	// ObservedPrimary is the pod name the sentinel currently believes
	// is the primary. Empty before the sentinel has converged on a
	// view; non-empty thereafter (refreshed on each observation pass).
	ObservedPrimary *string `json:"observedPrimary,omitempty"`
	// ObservedReplicas is the set of pod names the sentinel currently
	// sees as connected, non-primary replicas. Order is not
	// significant; the operator sorts on aggregation. Empty list is
	// legal (single-replica lab clusters).
	ObservedReplicas []string `json:"observedReplicas,omitempty"`
	// QuorumReachable indicates whether this sentinel pod can see at
	// least `spec.sentinel.quorum` peer-sentinels online. The operator
	// requires every aggregated record to report `true` before the
	// triple-check failover rule will fire.
	QuorumReachable *bool `json:"quorumReachable,omitempty"`
	// LastObservedTime is the wall-clock timestamp of the most
	// recent observation pass that produced this status. Stale
	// records (older than the operator's freshness threshold) are
	// excluded from aggregation — the operator treats them as a
	// missing pod, not a stale observation, to avoid acting on data
	// the observer may have since corrected.
	LastObservedTime *v1.Time `json:"lastObservedTime,omitempty"`
	// Conditions reports the standard observation-pass status
	// conditions for this sentinel. Reserved condition types:
	// - "Reachable": the sentinel pod responds to operator probes
	// - "QuorumAchieved": peer-sentinel quorum is met
	// - "PrimaryConfirmed": ObservedPrimary has been seen by a
	// majority of sentinels (set by the operator post-aggregation
	// on the corresponding Valkey CR — NOT here)
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// SentinelQuorumStatusApplyConfiguration constructs a declarative configuration of the SentinelQuorumStatus type for use with
// apply.
func SentinelQuorumStatus() *SentinelQuorumStatusApplyConfiguration {
	return &SentinelQuorumStatusApplyConfiguration{}
}

// WithObservedPrimary sets the ObservedPrimary field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedPrimary field is set to the value of the last call.
func (b *SentinelQuorumStatusApplyConfiguration) WithObservedPrimary(value string) *SentinelQuorumStatusApplyConfiguration {
	b.ObservedPrimary = &value
	return b
}

// WithObservedReplicas adds the given value to the ObservedReplicas field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ObservedReplicas field.
func (b *SentinelQuorumStatusApplyConfiguration) WithObservedReplicas(values ...string) *SentinelQuorumStatusApplyConfiguration {
	for i := range values {
		b.ObservedReplicas = append(b.ObservedReplicas, values[i])
	}
	return b
}

// WithQuorumReachable sets the QuorumReachable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QuorumReachable field is set to the value of the last call.
func (b *SentinelQuorumStatusApplyConfiguration) WithQuorumReachable(value bool) *SentinelQuorumStatusApplyConfiguration {
	b.QuorumReachable = &value
	return b
}

// WithLastObservedTime sets the LastObservedTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastObservedTime field is set to the value of the last call.
func (b *SentinelQuorumStatusApplyConfiguration) WithLastObservedTime(value v1.Time) *SentinelQuorumStatusApplyConfiguration {
	b.LastObservedTime = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *SentinelQuorumStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *SentinelQuorumStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
