/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ServiceEndpointApplyConfiguration represents a declarative configuration of the ServiceEndpoint type for use
// with apply.
//
// ServiceEndpoint is a per-Service shape (type, annotations, source ranges).
type ServiceEndpointApplyConfiguration struct {
	// Type selects the Service shape. The first three are standard Kubernetes
	// Service types; `Headless` is an operator-level abstraction that maps to
	// `type: ClusterIP, clusterIP: None` — exposed as a top-level enum value
	// because direct-pod addressing is a first-class deployment topology for
	// Valkey clients that prefer per-replica DNS over Service load-balancing.
	Type        *string           `json:"type,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
	// LoadBalancerSourceRanges restricts ingress when type=LoadBalancer.
	// Required (non-empty) when type=LoadBalancer.
	LoadBalancerSourceRanges []string `json:"loadBalancerSourceRanges,omitempty"`
	ExternalTrafficPolicy    *string  `json:"externalTrafficPolicy,omitempty"`
}

// ServiceEndpointApplyConfiguration constructs a declarative configuration of the ServiceEndpoint type for use with
// apply.
func ServiceEndpoint() *ServiceEndpointApplyConfiguration {
	return &ServiceEndpointApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ServiceEndpointApplyConfiguration) WithType(value string) *ServiceEndpointApplyConfiguration {
	b.Type = &value
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *ServiceEndpointApplyConfiguration) WithAnnotations(entries map[string]string) *ServiceEndpointApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithLoadBalancerSourceRanges adds the given value to the LoadBalancerSourceRanges field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LoadBalancerSourceRanges field.
func (b *ServiceEndpointApplyConfiguration) WithLoadBalancerSourceRanges(values ...string) *ServiceEndpointApplyConfiguration {
	for i := range values {
		b.LoadBalancerSourceRanges = append(b.LoadBalancerSourceRanges, values[i])
	}
	return b
}

// WithExternalTrafficPolicy sets the ExternalTrafficPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternalTrafficPolicy field is set to the value of the last call.
func (b *ServiceEndpointApplyConfiguration) WithExternalTrafficPolicy(value string) *ServiceEndpointApplyConfiguration {
	b.ExternalTrafficPolicy = &value
	return b
}
