/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// ValkeyPodSpecApplyConfiguration represents a declarative configuration of the ValkeyPodSpec type for use
// with apply.
//
// ValkeyPodSpec is the data-plane pod shape.
type ValkeyPodSpecApplyConfiguration struct {
	// Replicas is the number of Valkey data pods, including the primary.
	// Defaulter stamps a per-mode baseline when unset: 1 for standalone,
	// 2 for replication. No CRD-level default — the mode-aware default has
	// to live in the defaulter so the per-mode value can vary, and a
	// CRD-level default would race the defaulter (the apiserver would
	// stamp 1 before the webhook saw the zero value).
	Replicas *int32 `json:"replicas,omitempty"`
	// Resources sets requests and limits on the valkey container. Defaults
	// are stamped by the defaulting webhook to honour QoS class targets.
	Resources *v1.ResourceRequirements `json:"resources,omitempty"`
	// Persistence describes the PVC. Required for replication/sentinel
	// modes; optional for standalone (emptyDir when unset).
	Persistence *PersistenceSpecApplyConfiguration `json:"persistence,omitempty"`
	// CustomLivenessProbe overrides the operator's tcpSocket liveness
	// probe. Only the numeric timing fields may be changed; the validating
	// webhook rejects handler changes.
	CustomLivenessProbe *v1.Probe `json:"customLivenessProbe,omitempty"`
	// CustomReadinessProbe overrides the operator's exec-on-loopback
	// readiness probe. Same handler restriction as liveness.
	CustomReadinessProbe *v1.Probe `json:"customReadinessProbe,omitempty"`
	// ReadinessGate gates pod readiness on replication-lag observation.
	// Has no effect for standalone (single pod, no replication peer).
	ReadinessGate             *ReadinessGateSpecApplyConfiguration `json:"readinessGate,omitempty"`
	Affinity                  *v1.Affinity                         `json:"affinity,omitempty"`
	Tolerations               []v1.Toleration                      `json:"tolerations,omitempty"`
	NodeSelector              map[string]string                    `json:"nodeSelector,omitempty"`
	TopologySpreadConstraints []v1.TopologySpreadConstraint        `json:"topologySpreadConstraints,omitempty"`
	PriorityClassName         *string                              `json:"priorityClassName,omitempty"`
	DNSConfig                 *v1.PodDNSConfig                     `json:"dnsConfig,omitempty"`
	PodAnnotations            map[string]string                    `json:"podAnnotations,omitempty"`
	PodLabels                 map[string]string                    `json:"podLabels,omitempty"`
	SecurityContext           *v1.PodSecurityContext               `json:"securityContext,omitempty"`
	// Configuration is a raw valkey.conf snippet appended to the
	// operator-rendered base config. Banned directives are rejected by the
	// validating webhook (operator-managed networking, peer addressing,
	// sentinel monitoring).
	Configuration *string `json:"configuration,omitempty"`
	// ConfigurationOverrides is a directive→value map that merges over
	// `Configuration` with key-level replace semantics: the map value wins
	// for any directive that appears in both. Banned directives are
	// rejected here too. Merge logic ships with the config-rendering stage.
	ConfigurationOverrides map[string]string `json:"configurationOverrides,omitempty"`
	// PDB overrides the derived PodDisruptionBudget. Default
	// `minAvailable = replicas - 1` when unset (replicas >= 2).
	PDB *PDBSpecApplyConfiguration `json:"pdb,omitempty"`
	// MinReplicasToWrite gates writes when fewer than this many
	// replicas are connected to the primary. Maps to valkey.conf's
	// `min-replicas-to-write` directive. Floor 1 — values below
	// (i.e., 0) disable the gate entirely in Valkey, which means a
	// primary disconnected from all replicas continues accepting
	// writes that can never be replicated. The defaulter stamps 1 for
	// replication and sentinel modes when unset (an enforced data-safety
	// floor, not opt-in); standalone has no replicas, so the field stays
	// nil and the operator omits the directive. A user may set a stricter
	// value; the operator renders the field only when non-nil.
	// Availability note: a replicas=1 replication/sentinel cluster refuses
	// writes whenever its single replica is down or lagging beyond
	// minReplicasMaxLag — including during the operator's own rolling
	// restart of that replica. This is the deliberate
	// safety-over-availability trade-off; replicas>=2 preserves write
	// availability across pod updates.
	MinReplicasToWrite *int32 `json:"minReplicasToWrite,omitempty"`
	// MinReplicasMaxLag is the maximum tolerated replication lag
	// (in seconds) before a replica counts as "not connected" for
	// the MinReplicasToWrite gate. Maps to valkey.conf's
	// `min-replicas-max-lag`. Floor 10s — tighter values would
	// force-degrade on normal replication blips under load.
	MinReplicasMaxLag *int32 `json:"minReplicasMaxLag,omitempty"`
}

// ValkeyPodSpecApplyConfiguration constructs a declarative configuration of the ValkeyPodSpec type for use with
// apply.
func ValkeyPodSpec() *ValkeyPodSpecApplyConfiguration {
	return &ValkeyPodSpecApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ValkeyPodSpecApplyConfiguration) WithReplicas(value int32) *ValkeyPodSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *ValkeyPodSpecApplyConfiguration) WithResources(value v1.ResourceRequirements) *ValkeyPodSpecApplyConfiguration {
	b.Resources = &value
	return b
}

// WithPersistence sets the Persistence field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Persistence field is set to the value of the last call.
func (b *ValkeyPodSpecApplyConfiguration) WithPersistence(value *PersistenceSpecApplyConfiguration) *ValkeyPodSpecApplyConfiguration {
	b.Persistence = value
	return b
}

// WithCustomLivenessProbe sets the CustomLivenessProbe field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomLivenessProbe field is set to the value of the last call.
func (b *ValkeyPodSpecApplyConfiguration) WithCustomLivenessProbe(value v1.Probe) *ValkeyPodSpecApplyConfiguration {
	b.CustomLivenessProbe = &value
	return b
}

// WithCustomReadinessProbe sets the CustomReadinessProbe field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomReadinessProbe field is set to the value of the last call.
func (b *ValkeyPodSpecApplyConfiguration) WithCustomReadinessProbe(value v1.Probe) *ValkeyPodSpecApplyConfiguration {
	b.CustomReadinessProbe = &value
	return b
}

// WithReadinessGate sets the ReadinessGate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadinessGate field is set to the value of the last call.
func (b *ValkeyPodSpecApplyConfiguration) WithReadinessGate(value *ReadinessGateSpecApplyConfiguration) *ValkeyPodSpecApplyConfiguration {
	b.ReadinessGate = value
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *ValkeyPodSpecApplyConfiguration) WithAffinity(value v1.Affinity) *ValkeyPodSpecApplyConfiguration {
	b.Affinity = &value
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *ValkeyPodSpecApplyConfiguration) WithTolerations(values ...v1.Toleration) *ValkeyPodSpecApplyConfiguration {
	for i := range values {
		b.Tolerations = append(b.Tolerations, values[i])
	}
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *ValkeyPodSpecApplyConfiguration) WithNodeSelector(entries map[string]string) *ValkeyPodSpecApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithTopologySpreadConstraints adds the given value to the TopologySpreadConstraints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TopologySpreadConstraints field.
func (b *ValkeyPodSpecApplyConfiguration) WithTopologySpreadConstraints(values ...v1.TopologySpreadConstraint) *ValkeyPodSpecApplyConfiguration {
	for i := range values {
		b.TopologySpreadConstraints = append(b.TopologySpreadConstraints, values[i])
	}
	return b
}

// WithPriorityClassName sets the PriorityClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PriorityClassName field is set to the value of the last call.
func (b *ValkeyPodSpecApplyConfiguration) WithPriorityClassName(value string) *ValkeyPodSpecApplyConfiguration {
	b.PriorityClassName = &value
	return b
}

// WithDNSConfig sets the DNSConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DNSConfig field is set to the value of the last call.
func (b *ValkeyPodSpecApplyConfiguration) WithDNSConfig(value v1.PodDNSConfig) *ValkeyPodSpecApplyConfiguration {
	b.DNSConfig = &value
	return b
}

// WithPodAnnotations puts the entries into the PodAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodAnnotations field,
// overwriting an existing map entries in PodAnnotations field with the same key.
func (b *ValkeyPodSpecApplyConfiguration) WithPodAnnotations(entries map[string]string) *ValkeyPodSpecApplyConfiguration {
	if b.PodAnnotations == nil && len(entries) > 0 {
		b.PodAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PodAnnotations[k] = v
	}
	return b
}

// WithPodLabels puts the entries into the PodLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodLabels field,
// overwriting an existing map entries in PodLabels field with the same key.
func (b *ValkeyPodSpecApplyConfiguration) WithPodLabels(entries map[string]string) *ValkeyPodSpecApplyConfiguration {
	if b.PodLabels == nil && len(entries) > 0 {
		b.PodLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PodLabels[k] = v
	}
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *ValkeyPodSpecApplyConfiguration) WithSecurityContext(value v1.PodSecurityContext) *ValkeyPodSpecApplyConfiguration {
	b.SecurityContext = &value
	return b
}

// WithConfiguration sets the Configuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Configuration field is set to the value of the last call.
func (b *ValkeyPodSpecApplyConfiguration) WithConfiguration(value string) *ValkeyPodSpecApplyConfiguration {
	b.Configuration = &value
	return b
}

// WithConfigurationOverrides puts the entries into the ConfigurationOverrides field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ConfigurationOverrides field,
// overwriting an existing map entries in ConfigurationOverrides field with the same key.
func (b *ValkeyPodSpecApplyConfiguration) WithConfigurationOverrides(entries map[string]string) *ValkeyPodSpecApplyConfiguration {
	if b.ConfigurationOverrides == nil && len(entries) > 0 {
		b.ConfigurationOverrides = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ConfigurationOverrides[k] = v
	}
	return b
}

// WithPDB sets the PDB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PDB field is set to the value of the last call.
func (b *ValkeyPodSpecApplyConfiguration) WithPDB(value *PDBSpecApplyConfiguration) *ValkeyPodSpecApplyConfiguration {
	b.PDB = value
	return b
}

// WithMinReplicasToWrite sets the MinReplicasToWrite field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinReplicasToWrite field is set to the value of the last call.
func (b *ValkeyPodSpecApplyConfiguration) WithMinReplicasToWrite(value int32) *ValkeyPodSpecApplyConfiguration {
	b.MinReplicasToWrite = &value
	return b
}

// WithMinReplicasMaxLag sets the MinReplicasMaxLag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinReplicasMaxLag field is set to the value of the last call.
func (b *ValkeyPodSpecApplyConfiguration) WithMinReplicasMaxLag(value int32) *ValkeyPodSpecApplyConfiguration {
	b.MinReplicasMaxLag = &value
	return b
}
