/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ValkeyStatusApplyConfiguration represents a declarative configuration of the ValkeyStatus type for use
// with apply.
//
// ValkeyStatus is the observed state.
type ValkeyStatusApplyConfiguration struct {
	// Conditions reflect the current state of the Valkey resource.
	// Standard Kubernetes condition semantics apply. Notable
	// operator-specific condition types:
	//
	// - Ready:               True when the CR is fully reconciled
	// and all replicas are observed Ready.
	// - Available:           True when at least one replica is
	// observed Ready (writes routable).
	// - Progressing:         True while the operator is actively
	// making changes (rollout / bootstrap).
	// - Reconciled:          True when the most recent reconcile
	// pass returned no error.
	// - Degraded:            True when an operational signal blocks
	// forward progress (split-brain, rollout
	// stalled, HA floor not met, quorum loss).
	// - ReplicationHealthy:  True when replication-mode replicas
	// are connected and within the lag floor.
	// - BootstrapComplete:   True once the seed-bootstrap latched.
	// - PrimaryConfirmed:    True when a strict majority of fresh
	// SentinelQuorum records agree on the
	// observed primary pod. Sentinel mode
	// only. Unknown before the first
	// SentinelQuorum write lands.
	// - QuorumLost:          True when the sentinel-quorum
	// suppression gate is active. The gate
	// flips True only after ≥ the configured
	// loss threshold (default 60s) of
	// continuously-reachable-but-NOQUORUM
	// observations — transient sentinel
	// disagreement on a single poll does
	// NOT flip this True. The gate flips
	// False after the configured recovery
	// hysteresis (default 2 consecutive OK
	// polls). Unknown when no fresh
	// SentinelQuorum observations exist
	// (e.g., immediately after CR creation).
	// Sentinel mode only; False for
	// standalone / replication.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// Phase is a single cosmetic string derived from Conditions per
	// the API conventions doc. Surfaces in `kubectl get` columns and
	// dashboards; the operator's own logic always reads Conditions
	// directly. Values: Pending | Progressing | Available | Ready |
	// Degraded | Paused.
	Phase *string `json:"phase,omitempty"`
	// Rollout tracks the operator-driven rollout substate. Populated
	// only while a rollout (PVC resize, config-change, image bump) is
	// in flight; cleared by the operator once the substate machine
	// reaches its terminal phase.
	Rollout *RolloutStatusApplyConfiguration `json:"rollout,omitempty"`
	// PrimaryPod is the name of the pod a strict majority of fresh
	// SentinelQuorum records agree is the current primary, derived
	// each reconcile by the operator-side aggregator. Empty when no
	// majority is reached, when all SentinelQuorum records are stale
	// beyond the freshness window, or when the CR is not in sentinel
	// mode. Pairs with Conditions[type=PrimaryConfirmed]: True when
	// PrimaryPod is non-empty and the majority condition was met,
	// False otherwise.
	PrimaryPod *string `json:"primaryPod,omitempty"`
}

// ValkeyStatusApplyConfiguration constructs a declarative configuration of the ValkeyStatus type for use with
// apply.
func ValkeyStatus() *ValkeyStatusApplyConfiguration {
	return &ValkeyStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ValkeyStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ValkeyStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ValkeyStatusApplyConfiguration) WithPhase(value string) *ValkeyStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithRollout sets the Rollout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rollout field is set to the value of the last call.
func (b *ValkeyStatusApplyConfiguration) WithRollout(value *RolloutStatusApplyConfiguration) *ValkeyStatusApplyConfiguration {
	b.Rollout = value
	return b
}

// WithPrimaryPod sets the PrimaryPod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrimaryPod field is set to the value of the last call.
func (b *ValkeyStatusApplyConfiguration) WithPrimaryPod(value string) *ValkeyStatusApplyConfiguration {
	b.PrimaryPod = &value
	return b
}
