/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	apiv1beta1 "github.com/ioxie/velkir/api/v1beta1"
)

// ValkeySpecApplyConfiguration represents a declarative configuration of the ValkeySpec type for use
// with apply.
//
// ValkeySpec defines the desired state of a Valkey deployment.
//
// Cross-field invariants are expressed as CEL rules on the schema below.
// Rules referring to `sentinel` are inert until `mode` accepts `sentinel`;
// they are written eagerly so the relaxation in later stages is purely a
// `Mode` enum widening.
// Rule 1 (mode immutability) is inert at v1beta1 because the mode enum
// only admits `standalone`; it activates the moment the enum widens to
// admit replication or sentinel.
// Cross-field check; defense-in-depth against future relaxation of the
// SentinelPodSpec-level Minimum=2 / Maximum=replicas bounds.
// Trivially-satisfied today (valkey.replicas Minimum=1 catches replicas=0
// first); kept to codify the intent ("bootstrap requires at least one
// valkey pod") so a future Minimum relaxation doesn't silently uncover
// the gap. Not exercised by tests because the precondition is unreachable
// without bypassing field-level validation.
// Trivially-satisfied today (image.exporter.repository default is
// non-empty and MinLength=1 catches an explicit empty); kept as a guard
// against future default removal. Not exercised by tests because the
// precondition is unreachable without bypassing field-level validation.
// Storage monotonicity: persistence.size may grow but never
// shrink. Growth is handled by the operator-driven PVC resize sub-
// state-machine; shrinking would require a full data-plane rebuild
// and is hard-rejected. The rule short-circuits on CREATE (oldSelf
// has no persistence to compare against).
//
// Rollout MaxLagBytes ceiling: the field-level Maximum on
// rollout.maxLagBytes already bounds the value at 10 MiB; this CEL rule
// codifies the same intent at spec level so a future field-level
// relaxation (e.g. lifting Maximum to support larger replication
// windows) does not silently uncover the cap. Pure upper-bound check;
// short-circuits when rollout or maxLagBytes is unset.
type ValkeySpecApplyConfiguration struct {
	// Mode selects the deployment topology. Immutable in v1beta1.
	Mode *apiv1beta1.Mode `json:"mode,omitempty"`
	// Image pins the container image for each component.
	Image *ImageSpecApplyConfiguration `json:"image,omitempty"`
	// Valkey is the data-plane pod shape.
	Valkey *ValkeyPodSpecApplyConfiguration `json:"valkey,omitempty"`
	// Sentinel is the sentinel pod shape. Required iff mode=sentinel.
	Sentinel *SentinelPodSpecApplyConfiguration `json:"sentinel,omitempty"`
	// Auth references Secrets carrying the Valkey default-user password and,
	// when mode=sentinel, an optional sentinel auth pair.
	Auth *AuthSpecApplyConfiguration `json:"auth,omitempty"`
	// Service shapes the client- and sentinel-facing Services.
	Service *ServiceSpecApplyConfiguration `json:"service,omitempty"`
	// Metrics gates the per-pod exporter sidecar and PodMonitor.
	Metrics *MetricsSpecApplyConfiguration `json:"metrics,omitempty"`
	// BootstrapNode seeds a new deployment as a replica of an existing
	// external primary, for migrations.
	BootstrapNode *BootstrapNodeSpecApplyConfiguration `json:"bootstrapNode,omitempty"`
	// Rollout governs rolling-update behaviour. Best-practice defaults
	// applied when fields are omitted; user overrides emit Warning events.
	Rollout *RolloutSpecApplyConfiguration `json:"rollout,omitempty"`
	// PVCRetentionPolicy controls PVC lifecycle on CR deletion. Retain is
	// the safe default; Delete cascades via owner-ref injection.
	//
	// Backed by a finalizer (`velkir.ioxie.dev/pvc-retention`): the
	// apiserver blocks the CR's GC until the operator's deletion path
	// has applied the policy and stripped the finalizer. So a CR
	// deletion issued while the operator is offline (pod restart, leader
	// handover, full outage) sits in `Terminating` until the operator
	// wakes up and completes the policy — there is no best-effort
	// window where Retain might incorrectly cascade or Delete might
	// leave PVCs orphaned.
	PVCRetentionPolicy *apiv1beta1.PVCRetentionPolicy `json:"pvcRetentionPolicy,omitempty"`
	// FeatureGates toggles operator-recognised features on a per-CR
	// basis. Each key's default (when the key is absent from the map)
	// is the safe-by-default behaviour; users opt out by explicitly
	// setting the key to false. Unknown keys are accepted for forward
	// compatibility — the validating webhook emits a Warning per
	// unknown key in `kubectl apply` output without blocking the
	// request, and the operator logs a startup warning for each.
	// Recognised keys (default value in parentheses):
	// - UpgradePreflight (true) — when false, bypasses the major-
	// version-downgrade rejection in the runtime version-compat
	// preflight. Testbed / disaster-recovery only; the operator
	// emits ValkeyImageTransitionOverridden on the audit trail
	// each time the bypass fires.
	FeatureGates map[string]bool `json:"featureGates,omitempty"`
}

// ValkeySpecApplyConfiguration constructs a declarative configuration of the ValkeySpec type for use with
// apply.
func ValkeySpec() *ValkeySpecApplyConfiguration {
	return &ValkeySpecApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *ValkeySpecApplyConfiguration) WithMode(value apiv1beta1.Mode) *ValkeySpecApplyConfiguration {
	b.Mode = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ValkeySpecApplyConfiguration) WithImage(value *ImageSpecApplyConfiguration) *ValkeySpecApplyConfiguration {
	b.Image = value
	return b
}

// WithValkey sets the Valkey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Valkey field is set to the value of the last call.
func (b *ValkeySpecApplyConfiguration) WithValkey(value *ValkeyPodSpecApplyConfiguration) *ValkeySpecApplyConfiguration {
	b.Valkey = value
	return b
}

// WithSentinel sets the Sentinel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sentinel field is set to the value of the last call.
func (b *ValkeySpecApplyConfiguration) WithSentinel(value *SentinelPodSpecApplyConfiguration) *ValkeySpecApplyConfiguration {
	b.Sentinel = value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *ValkeySpecApplyConfiguration) WithAuth(value *AuthSpecApplyConfiguration) *ValkeySpecApplyConfiguration {
	b.Auth = value
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *ValkeySpecApplyConfiguration) WithService(value *ServiceSpecApplyConfiguration) *ValkeySpecApplyConfiguration {
	b.Service = value
	return b
}

// WithMetrics sets the Metrics field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metrics field is set to the value of the last call.
func (b *ValkeySpecApplyConfiguration) WithMetrics(value *MetricsSpecApplyConfiguration) *ValkeySpecApplyConfiguration {
	b.Metrics = value
	return b
}

// WithBootstrapNode sets the BootstrapNode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootstrapNode field is set to the value of the last call.
func (b *ValkeySpecApplyConfiguration) WithBootstrapNode(value *BootstrapNodeSpecApplyConfiguration) *ValkeySpecApplyConfiguration {
	b.BootstrapNode = value
	return b
}

// WithRollout sets the Rollout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rollout field is set to the value of the last call.
func (b *ValkeySpecApplyConfiguration) WithRollout(value *RolloutSpecApplyConfiguration) *ValkeySpecApplyConfiguration {
	b.Rollout = value
	return b
}

// WithPVCRetentionPolicy sets the PVCRetentionPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PVCRetentionPolicy field is set to the value of the last call.
func (b *ValkeySpecApplyConfiguration) WithPVCRetentionPolicy(value apiv1beta1.PVCRetentionPolicy) *ValkeySpecApplyConfiguration {
	b.PVCRetentionPolicy = &value
	return b
}

// WithFeatureGates puts the entries into the FeatureGates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the FeatureGates field,
// overwriting an existing map entries in FeatureGates field with the same key.
func (b *ValkeySpecApplyConfiguration) WithFeatureGates(entries map[string]bool) *ValkeySpecApplyConfiguration {
	if b.FeatureGates == nil && len(entries) > 0 {
		b.FeatureGates = make(map[string]bool, len(entries))
	}
	for k, v := range entries {
		b.FeatureGates[k] = v
	}
	return b
}
